#+TITLE: Notes

* =chicago=
Immediate observation: ggplot kind of "just knows" what to do with dates or
strings (or perhaps this is part of the csv reader?) whereas w/ =plot= I am
currently in the process of digging up how to get dates to work and I had to
=map string->number=

I had to wrangle the CSV by hand -- there isn't interoperation between =plot=
and =csv-reading=. Also it looks like =csv= on the Racket package index is...
almost useless

There's nothing to parse dates, and since I'm currently attempting to turn my
brain off and think in the mind of an R programmer, I'm using the =gregor=
library for this. Also note that I actually, again, have to parse the date
whereas it's magically(tm) handled in ggplot2

The font family names in racket/draw don't really make any sense (why is
monospace "modern"?)

Subtitle? Caption? Figure tag?
* =gapminder=
Data wrangling in Racket with =data-frame= is like pulling teeth, let's not do
that. It probably shouldn't be like pulling teeth though...

The =data-frame= library doesn't read the literal string "NA" as an NA value --
should it? (probably not)

=in-data-frame= should have a =#:filter= like =df-select=. Actually, there should
be better filtering in general here --- with ggplot, you don't even have to think
about stratifying on a variable, it just happens

=df-series-names= might want to be in the order they appear in the table

The =geom_smooth= method in R with the =gam= fit works very well for this data, but
it isn't available here

In general, stratification of data along a variable (and thereby adding a legend)
could be a lot better
* 2021-02-15
Fix whatever's going on with =log-transform=
